const fs = require('fs');
const path = `./.env`;
const vars = `
REACT_APP_FIREBASE_API_KEY=${process.env.REACT_APP_FIREBASE_API_KEY}\n
REACT_APP_FIREBASE_AUTH_DOMAIN=${process.env.REACT_APP_FIREBASE_AUTH_DOMAIN}\n
REACT_APP_FIREBASE_PROJECT_ID=${process.env.REACT_APP_FIREBASE_PROJECT_ID}\n
REACT_APP_FIREBASE_STORAGE_BUCKET=${process.env.REACT_APP_FIREBASE_STORAGE_BUCKET}\n
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}\n
REACT_APP_FIREBASE_APP_ID=${process.env.REACT_APP_FIREBASE_APP_ID}\n
`;
fs.writeFileSync(path, vars);
